# Generated by Django 5.0.3 on 2024-08-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spayment",
            old_name="name",
            new_name="sitter_names",
        ),
    ]
