# Generated by Django 5.0.3 on 2024-08-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_name_spayment_sitter_names"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitter",
            old_name="name",
            new_name="name_id",
        ),
        migrations.RenameField(
            model_name="spayment",
            old_name="sitter_names",
            new_name="name_id",
        ),
    ]
