# Generated by Django 5.0.3 on 2024-08-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_name_sitter_name_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitter",
            old_name="name_id",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="spayment",
            old_name="name_id",
            new_name="name",
        ),
    ]
