# Generated by Django 5.0.3 on 2024-05-14 12:20

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babesform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_stay', models.CharField(default=None, max_length=200)),
                ('b_name', models.CharField(max_length=200)),
                ('age', models.CharField(default=0, max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('location', models.CharField(default=None, max_length=50, null=True)),
                ('sponsor', models.CharField(max_length=200)),
                ('parentsname', models.CharField(max_length=200)),
                ('babysno', models.CharField(default=0, max_length=200)),
                ('timein', models.DateTimeField()),
                ('brought_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category_doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorystay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shopform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('Fruits', 'Fruits'), ('Diapers', 'Diapers'), ('Milk', 'Milk'), ('Toys', 'Toys')], max_length=100)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_received', models.IntegerField(blank=True, default=0, null=True)),
                ('Total_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('Date_of_purchase', models.DateField(default=datetime.datetime(2024, 5, 14, 12, 20, 58, 416654, tzinfo=datetime.timezone.utc))),
                ('quantity_issued_out', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_at_hand', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sittersform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200)),
                ('age', models.CharField(default=0, max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('next_of_kin', models.CharField(max_length=200)),
                ('level_of_education', models.CharField(max_length=50)),
                ('nin', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=0, default=3000, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('numbers_of_babies_attended_to', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='B_departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_taking_baby', models.CharField(max_length=200)),
                ('telephone_no', models.CharField(max_length=200)),
                ('timeout', models.DateTimeField()),
                ('babyno', models.IntegerField(default=0)),
                ('comments', models.TextField(max_length=500)),
                ('b_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.babesform')),
            ],
        ),
        migrations.CreateModel(
            name='Bpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payno', models.IntegerField(default=0)),
                ('currency', models.IntegerField(choices=[(10000, '10000'), (15000, '15000'), (300000, '300000'), (450000, '450000')], default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.babesform')),
                ('c_payment_id', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='home.categorystay')),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_doll', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('c_doll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category_doll')),
            ],
        ),
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(default=0)),
                ('amount_received', models.IntegerField(default=0)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('unit_price', models.IntegerField(default=0)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doll')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.babesform')),
            ],
        ),
        migrations.CreateModel(
            name='Sarrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timein', models.TimeField(default=django.utils.timezone.now)),
                ('sittersno', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('s_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sittersform')),
            ],
        ),
    ]
