# Generated by Django 5.0.3 on 2024-05-20 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopform',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 8, 25, 22, 105056, tzinfo=datetime.timezone.utc)),
        ),
    ]
