# Generated by Django 5.0.3 on 2024-05-14 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babesform',
            name='c_stay',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shopform',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 12, 22, 48, 209422, tzinfo=datetime.timezone.utc)),
        ),
    ]
