# Generated by Django 5.0.3 on 2024-08-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_shopstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sitter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
