# Generated by Django 5.0.3 on 2024-05-20 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_payment_id_alter_shopform_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopform',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 18, 50, 11, 192130, tzinfo=datetime.timezone.utc)),
        ),
    ]
