# Generated by Django 5.0.3 on 2024-08-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_name_id_sitter_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopform",
            name="baby_names",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.babesform",
            ),
        ),
    ]
