# Generated by Django 5.0.3 on 2024-07-14 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_shopform_date_of_purchase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopform",
            name="quantity_issued_out",
        ),
        migrations.RemoveField(
            model_name="shopform",
            name="quantity_received",
        ),
        migrations.RemoveField(
            model_name="shopform",
            name="stock_at_hand",
        ),
        migrations.AddField(
            model_name="shopform",
            name="unit_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shopform",
            name="Date_of_purchase",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 14, 16, 16, 45, 776977, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
