# Generated by Django 5.0.3 on 2024-07-14 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_shopform_quantity_issued_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopform",
            name="Date_of_purchase",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 14, 16, 24, 42, 388937, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
