# Generated by Django 5.0.3 on 2024-07-14 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_remove_shopform_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopform",
            name="Date_of_purchase",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
