# Generated by Django 5.0.3 on 2024-07-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_shopform_date_of_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopform",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
